import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mystry Message",
  description: "Generated by create next app",
};

export default function AppLayout({
    children,
  }: LayoutProps<"/">) {
    return (
      <div className="min-h-screen flex flex-col">
        <Navbar />
        {children}
      </div>
    );
}
